"""Stable dilute-band area extraction and inference."""

from .components import BandComponent, label_dilute_bands
from .bayesian import (
    BayesianResult,
    MCMCConfig,
    MCMCDiagnostics,
    coupled_area_model,
    run_bayesian_inference,
)
from .characterization import DetectedBand, characterize_band
from .density import SurfaceGrid
from .inference import (
    HessianDiagnostics,
    OptimizationResult,
    OptimizationRun,
    empirical_parameters,
    optimize_parameters,
)
from .model import (
    FITTED_PARAMETER_NAMES,
    PARAMETER_NAMES,
    JITTER,
    PersistentRateBlock,
    Scaling,
    StateSpaceSequence,
    TrainingTransitions,
    TransitionBlock,
    build_transition_blocks,
    build_state_space_sequences,
    build_persistent_rate_blocks,
    conservative_segment_slope,
    conservative_segment_slopes,
    estimate_slope_variance,
    negative_log_likelihood,
    parameter_negative_log_likelihood,
    persistent_innovations,
    positive_parameters,
    prepare_training_transitions,
    raw_parameters,
    transition,
    transition_log_density,
)
from .segments import StableSegment, build_stable_segments
from .tracking import (
    BandTracker,
    DetectionFrame,
    EventCode,
    EventRecord,
    TrackedBand,
    TrackedFrame,
)
from .validation import ValidationResult, validate_posterior
from .workflow import AnalysisConfig, LagOutcome, run_analysis, stable_lags

__all__ = [
    "BandComponent",
    "BandTracker",
    "BayesianResult",
    "DetectedBand",
    "DetectionFrame",
    "EventCode",
    "EventRecord",
    "HessianDiagnostics",
    "JITTER",
    "LagOutcome",
    "MCMCConfig",
    "MCMCDiagnostics",
    "OptimizationResult",
    "OptimizationRun",
    "FITTED_PARAMETER_NAMES",
    "PARAMETER_NAMES",
    "PersistentRateBlock",
    "Scaling",
    "SurfaceGrid",
    "AnalysisConfig",
    "TrainingTransitions",
    "StableSegment",
    "TrackedBand",
    "TrackedFrame",
    "TransitionBlock",
    "ValidationResult",
    "build_transition_blocks",
    "build_stable_segments",
    "characterize_band",
    "coupled_area_model",
    "empirical_parameters",
    "StateSpaceSequence",
    "build_state_space_sequences",
    "build_persistent_rate_blocks",
    "conservative_segment_slope",
    "conservative_segment_slopes",
    "estimate_slope_variance",
    "label_dilute_bands",
    "negative_log_likelihood",
    "optimize_parameters",
    "parameter_negative_log_likelihood",
    "persistent_innovations",
    "positive_parameters",
    "prepare_training_transitions",
    "raw_parameters",
    "run_analysis",
    "run_bayesian_inference",
    "stable_lags",
    "transition",
    "transition_log_density",
    "validate_posterior",
]
