"""Stable dilute-band area extraction and inference."""

from .detection.components import BandComponent, label_dilute_bands
from .fitting.bayesian import (
    BayesianResult,
    MCMCConfig,
    MCMCDiagnostics,
    coupled_area_model,
    run_bayesian_inference,
)
from .detection.characterization import DetectedBand, characterize_band
from .detection.density import SurfaceGrid
from .fitting.inference import (
    HessianDiagnostics,
    OptimizationResult,
    OptimizationRun,
    empirical_parameters,
    optimize_parameters,
)
from .fitting.model import (
    PARAMETER_NAMES,
    JITTER,
    PersistentRateBlock,
    Scaling,
    StateSpaceSequence,
    TrainingTransitions,
    TransitionBlock,
    build_transition_blocks,
    build_state_space_sequences,
    build_persistent_rate_blocks,
    conservative_segment_slope,
    conservative_segment_slopes,
    estimate_slope_variance,
    negative_log_likelihood,
    parameter_negative_log_likelihood,
    persistent_innovations,
    positive_parameters,
    prepare_training_transitions,
    raw_parameters,
    transition,
    transition_log_density,
)
from .detection.chains import (
    ChainPlan,
    EventChain,
    KnotGrid,
    build_chains,
    build_event_chains,
    build_knot_grid,
    build_knot_grids,
    event_transitions,
    global_n_max,
    plan_chains,
)
from .detection.events import (
    EventCompositionError,
    EventStep,
    build_event_step,
    initial_slots,
    no_event_step,
    pack_areas,
    slot_mask,
)
from .detection.segments import StableSegment, build_stable_segments
from .detection.tracking import (
    BandTracker,
    DetectionFrame,
    EventCode,
    EventEdges,
    EventRecord,
    TrackedBand,
    TrackedFrame,
)
from .fitting.validation import ValidationResult, validate_posterior
from .pipeline.workflow import AnalysisConfig, LagOutcome, run_analysis, stable_lags

__all__ = [
    "BandComponent",
    "BandTracker",
    "BayesianResult",
    "ChainPlan",
    "DetectedBand",
    "DetectionFrame",
    "EventChain",
    "EventCode",
    "EventCompositionError",
    "EventEdges",
    "EventRecord",
    "EventStep",
    "HessianDiagnostics",
    "JITTER",
    "KnotGrid",
    "LagOutcome",
    "MCMCConfig",
    "MCMCDiagnostics",
    "OptimizationResult",
    "OptimizationRun",
    "PARAMETER_NAMES",
    "PersistentRateBlock",
    "Scaling",
    "SurfaceGrid",
    "AnalysisConfig",
    "TrainingTransitions",
    "StableSegment",
    "TrackedBand",
    "TrackedFrame",
    "TransitionBlock",
    "ValidationResult",
    "build_chains",
    "build_event_chains",
    "build_event_step",
    "build_knot_grid",
    "build_knot_grids",
    "build_transition_blocks",
    "build_stable_segments",
    "characterize_band",
    "coupled_area_model",
    "empirical_parameters",
    "event_transitions",
    "global_n_max",
    "plan_chains",
    "StateSpaceSequence",
    "build_state_space_sequences",
    "build_persistent_rate_blocks",
    "conservative_segment_slope",
    "conservative_segment_slopes",
    "estimate_slope_variance",
    "initial_slots",
    "label_dilute_bands",
    "negative_log_likelihood",
    "no_event_step",
    "optimize_parameters",
    "pack_areas",
    "slot_mask",
    "parameter_negative_log_likelihood",
    "persistent_innovations",
    "positive_parameters",
    "prepare_training_transitions",
    "raw_parameters",
    "run_analysis",
    "run_bayesian_inference",
    "stable_lags",
    "transition",
    "transition_log_density",
    "validate_posterior",
]
